/**
 * App catalogue.
 *
 * Apps are data, not hard-coded settings screens. Each store enables what it
 * needs; a feature that is not enabled is not rendered and, where it has a
 * server-side effect, not executed.
 */

export interface AppDefinitionSeed {
  key: string;
  nameAr: string;
  nameEn: string;
  descriptionAr: string;
  descriptionEn: string;
  category: 'general' | 'sales' | 'operations' | 'marketing' | 'security' | 'integrations';
  icon: string;
  settingsRoute: string | null;
  isCore: boolean;
  requiredFeature: string | null;
  defaultEnabled: boolean;
  position: number;
}

export const APP_DEFINITIONS: readonly AppDefinitionSeed[] = [
  {
    key: 'shopping_cart',
    nameAr: 'سلة التسوق',
    nameEn: 'Shopping cart',
    descriptionAr: 'يسمح للعميل بإضافة عدة منتجات قبل إتمام الطلب. عند التعطيل يشتري العميل منتجاً واحداً مباشرة.',
    descriptionEn: 'Let customers collect several products before checkout. When disabled, checkout is single-product and direct.',
    category: 'sales',
    icon: 'shopping-cart',
    settingsRoute: '/dashboard/settings/checkout',
    isCore: true,
    requiredFeature: null,
    defaultEnabled: true,
    position: 1,
  },
  {
    key: 'order_tracking',
    nameAr: 'تتبع الطلبات',
    nameEn: 'Order tracking',
    descriptionAr: 'صفحة عامة يستعلم فيها العميل عن حالة طلبه برقم الطلب ورقم الهاتف.',
    descriptionEn: 'A public page where customers look up their order by number and phone.',
    category: 'sales',
    icon: 'search',
    settingsRoute: '/dashboard/settings/security',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 2,
  },
  {
    key: 'thank_you_popup',
    nameAr: 'رسالة الشكر',
    nameEn: 'Thank-you popup',
    descriptionAr: 'رسالة تظهر للعميل بعد نجاح الطلب مع زر إجراء اختياري.',
    descriptionEn: 'A message shown after a successful order, with an optional action button.',
    category: 'sales',
    icon: 'party-popper',
    settingsRoute: '/dashboard/settings/checkout',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 3,
  },
  {
    key: 'trust_badges',
    nameAr: 'شارات الثقة',
    nameEn: 'Trust badges',
    descriptionAr: 'شارات مثل الدفع الآمن والإرجاع السهل تظهر في صفحة المنتج وإتمام الطلب.',
    descriptionEn: 'Badges such as secure payment and easy returns on the product and checkout pages.',
    category: 'sales',
    icon: 'shield-check',
    settingsRoute: '/dashboard/apps/trust-badges',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 4,
  },
  {
    key: 'quick_contact',
    nameAr: 'التواصل السريع',
    nameEn: 'Quick contact',
    descriptionAr: 'أزرار اتصال وواتساب عائمة داخل المتجر.',
    descriptionEn: 'Floating call and WhatsApp buttons in the storefront.',
    category: 'sales',
    icon: 'message-circle',
    settingsRoute: '/dashboard/apps/quick-contact',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 5,
  },
  {
    key: 'offer_campaigns',
    nameAr: 'حملات العروض',
    nameEn: 'Offer campaigns',
    descriptionAr: 'خصومات مؤقتة على منتجات مختارة بتواريخ بداية ونهاية.',
    descriptionEn: 'Time-boxed discounts on selected products.',
    category: 'marketing',
    icon: 'percent',
    settingsRoute: '/dashboard/campaigns',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 6,
  },
  {
    key: 'collections',
    nameAr: 'المجموعات',
    nameEn: 'Collections',
    descriptionAr: 'تجميع المنتجات في مجموعات تظهر في المتجر.',
    descriptionEn: 'Group products into collections shown in the storefront.',
    category: 'general',
    icon: 'layers',
    settingsRoute: '/dashboard/collections',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 7,
  },
  {
    key: 'custom_fields',
    nameAr: 'حقول مخصصة',
    nameEn: 'Custom fields',
    descriptionAr: 'حقول إضافية في نموذج إتمام الطلب.',
    descriptionEn: 'Extra fields on the checkout form.',
    category: 'general',
    icon: 'list-plus',
    settingsRoute: '/dashboard/settings/checkout',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 8,
  },
  {
    key: 'auto_agent_assignment',
    nameAr: 'الإسناد التلقائي للوكلاء',
    nameEn: 'Automatic agent assignment',
    descriptionAr: 'إسناد الطلبات الجديدة تلقائياً لوكلاء مركز الاتصال حسب المنتج.',
    descriptionEn: 'Route new orders to call-center agents by product.',
    category: 'operations',
    icon: 'user-check',
    settingsRoute: '/dashboard/call-center/rules',
    isCore: false,
    requiredFeature: 'call_center',
    defaultEnabled: false,
    position: 9,
  },
  {
    key: 'auto_shipping_assignment',
    nameAr: 'الإسناد التلقائي للشحن',
    nameEn: 'Automatic shipping assignment',
    descriptionAr: 'اختيار شركة التوصيل تلقائياً حسب المنطقة أو قيمة الطلب.',
    descriptionEn: 'Pick the carrier automatically by region or order value.',
    category: 'operations',
    icon: 'route',
    settingsRoute: '/dashboard/shipping/rules',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 10,
  },
  {
    key: 'abandoned_orders',
    nameAr: 'الطلبات المتروكة',
    nameEn: 'Abandoned checkouts',
    descriptionAr: 'تتبع السلات التي بدأ العميل إتمامها ولم يكملها.',
    descriptionEn: 'Track checkouts a customer started but did not complete.',
    category: 'marketing',
    icon: 'shopping-bag',
    settingsRoute: '/dashboard/abandoned',
    isCore: false,
    requiredFeature: 'abandoned_recovery',
    defaultEnabled: false,
    position: 11,
  },
  {
    key: 'fraud_protection',
    nameAr: 'حماية الطلبات المكررة',
    nameEn: 'Duplicate-order protection',
    descriptionAr: 'منع أو تعليم الطلبات المتكررة من نفس الرقم خلال فترة محددة.',
    descriptionEn: 'Block or flag repeated orders from the same phone within a window.',
    category: 'security',
    icon: 'shield-alert',
    settingsRoute: '/dashboard/settings/security',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 12,
  },
  {
    key: 'ip_blacklist',
    nameAr: 'قائمة حظر العناوين',
    nameEn: 'IP blacklist',
    descriptionAr: 'منع إنشاء الطلبات من عناوين IP محددة.',
    descriptionEn: 'Stop orders being created from specific IP addresses.',
    category: 'security',
    icon: 'ban',
    settingsRoute: '/dashboard/settings/security',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 13,
  },
  {
    key: 'google_sheets',
    nameAr: 'Google Sheets',
    nameEn: 'Google Sheets',
    descriptionAr: 'مزامنة الطلبات والمنتجات مع جدول بيانات.',
    descriptionEn: 'Sync orders and products with a spreadsheet.',
    category: 'integrations',
    icon: 'table',
    settingsRoute: '/dashboard/integrations',
    isCore: false,
    requiredFeature: 'integrations',
    defaultEnabled: false,
    position: 14,
  },
  {
    key: 'product_import',
    nameAr: 'استيراد المنتجات',
    nameEn: 'Product import',
    descriptionAr: 'استيراد المنتجات من ملف CSV أو منصة خارجية.',
    descriptionEn: 'Import products from a CSV file or an external platform.',
    category: 'integrations',
    icon: 'upload',
    settingsRoute: '/dashboard/integrations/import',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: true,
    position: 15,
  },
  {
    key: 'qr_generator',
    nameAr: 'مولّد QR',
    nameEn: 'QR generator',
    descriptionAr: 'إنشاء رمز QR لأي رابط داخل متجرك.',
    descriptionEn: 'Create a QR code for any link in your store.',
    category: 'general',
    icon: 'qr-code',
    settingsRoute: '/dashboard/apps/qr',
    isCore: false,
    requiredFeature: null,
    defaultEnabled: false,
    position: 16,
  },
  {
    key: 'store_builder',
    nameAr: 'بناء المتجر',
    nameEn: 'Store builder',
    descriptionAr: 'صفحات هبوط وقوالب وتخصيص بصري.',
    descriptionEn: 'Landing pages, themes and visual customisation.',
    category: 'marketing',
    icon: 'layout-template',
    settingsRoute: '/dashboard/pages',
    isCore: false,
    requiredFeature: 'landing_pages',
    defaultEnabled: true,
    position: 17,
  },
] as const;

export function getAppDefinition(key: string): AppDefinitionSeed | null {
  return APP_DEFINITIONS.find((app) => app.key === key) ?? null;
}
