import {
  Activity,
  Award,
  Ban,
  BarChart3,
  Check,
  Clock,
  Facebook,
  FileSpreadsheet,
  CreditCard,
  FileText,
  Ghost,
  Headphones,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  ListPlus,
  Lock,
  MapPin,
  MessageCircle,
  Music,
  Package,
  Palette,
  PartyPopper,
  Percent,
  Plug,
  Puzzle,
  QrCode,
  RefreshCw,
  Route,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sheet,
  Store,
  Table,
  Tags,
  Truck,
  Upload,
  UserCheck,
  UserCog,
  Users,
  Webhook,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icon registry.
 *
 * Icons are referenced by string from data (navigation, app catalogue, trust
 * badges) so those definitions stay serialisable and free of React imports.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  award: Award,
  ban: Ban,
  'bar-chart-3': BarChart3,
  check: Check,
  clock: Clock,
  'credit-card': CreditCard,
  facebook: Facebook,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  ghost: Ghost,
  headphones: Headphones,
  'layout-dashboard': LayoutDashboard,
  'layout-template': LayoutTemplate,
  layers: Layers,
  'list-plus': ListPlus,
  lock: Lock,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  music: Music,
  package: Package,
  palette: Palette,
  'party-popper': PartyPopper,
  percent: Percent,
  plug: Plug,
  puzzle: Puzzle,
  'qr-code': QrCode,
  refresh: RefreshCw,
  route: Route,
  'scroll-text': ScrollText,
  search: Search,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  sheet: Sheet,
  store: Store,
  table: Table,
  tags: Tags,
  truck: Truck,
  upload: Upload,
  'user-check': UserCheck,
  'user-cog': UserCog,
  users: Users,
  webhook: Webhook,
  zap: Zap,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = ICONS[name] ?? Package;
  return <Component className={className} aria-hidden />;
}

export function hasIcon(name: string): boolean {
  return name in ICONS;
}
